- id: kubectl-kustomize
  name: Build Kustomize manifests
  description: Builds a kustomize.yaml file into it's resulting manifests.
  entry: kubectl-kustomize.sh
  language: script
  file: kustomize.yaml
  types: []
