- id: kubectl-kustomize
  name: Build Kustomize manifests
  description: Builds a kustomize.yaml file into it's resulting manifests.
  entry: kubectl-kustomize
  language: script
  pass_filenames: false